config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get	'index', to: 'home#index'
  get	'about', to: 'home#about'

  [404,422,500].each do |code|
    get "#{code}", :to => "errors#show", :code => code, :defaults => {:format => :html}
  end

  resources :case_files
  resources :events
  resources :locations
  resources :people do
    resources :marks
  end
  # Configurables
  resources :anatomies
  resources :mark_types
  
  # Auth
  resources :users 
  resources :session, only: [:new,:create,:destroy]
end

app/models/person.rb
# Person class contains the descriptions of people and a narative of
# their life.
class Person < ActiveRecord::Base
  include PersonEnum
  has_many :event_people
  # @!attribute events [rw]
  # @return [Relation<Event>] Narrative for this persons life
  has_many :events,
           through: :event_people
  # @!attribute case_files
  # @return [Relation<CaseFile>] Cases this person was involved in
  has_many :case_files,
           -> { distinct },
           through: :events
  validate :validate_birth_event_count,
           :validate_death_event_count

  # @!attribute [rw] aliases
  # A list of the person's aliases
  # @return [Relation<Alias>]
  has_many :aliases, dependent: :destroy
  accepts_nested_attributes_for :aliases,
                                allow_destroy: true

  # @!attribute [rw] marks
  # The {Mark}s for this person.
  has_many :marks

  # The name of the person. This will return the default {Alias}.
  # @return [String]
  def name
    aliases.default_name.first.name
  rescue
    aliases.first.name
  end

  # @return The person's birth date, or nil if no birth event.
  def dob
    if birth.empty?
      return nil
    else
      return birth.first.date
    end
  end

  # @return The person's death date, or nil if no death event.
  def dod
    if death.empty?
      return nil
    else
      return death.first.date
    end
  end
  # @!attribute birth
  # @return [CollectionProxy<Event>] birth event of this person

  # @!attribute death
  # @return [CollectionProxy<Event>] death event of this person

  # @!attribute victim
  # @return [CollectionProxy<Event>] events where this person was
  # a victim

  # @!attribute perpetrator
  # @return [CollectionProxy<Event>] events where this person was
  # a perpetrator

  # @!attribute investigator
  # @return [CollectionProxy<Event>] events where this person was
  # an investigator
  EventPerson.categories.each do |type|
    type = type[0].to_sym
    has_many type,
             -> { where 'event_people.category' => type },
             through: :event_people,
             source: :event
  end

  # Return the description of this person.
  # @return [Hash<String,String>] All description elements which are known.
  def description
    description = {}
    description_fields.each do |v|
      attr = self[v]
      next if attr == 'unknown' || attr.nil?
      field = Person.human_attribute_name(v)
      attr = Person.human_attribute_name(attr)
      description[field] = attr
    end
    description
  end

  private

  # Validate that only one birth event is allowed per person
  def validate_birth_event_count
    errors.add(:birth, :multipleBirthEvents) if birth.size > 1
  end

  # Validate that only one death event is allowed per person
  def validate_death_event_count
    errors.add(:death, :multipleDeathEvents) if death.size > 1
  end

  # The fields used to describe a person
  def description_fields
    [:ic, :gender, :height, :build, :eye_colour,
     :hair_length, :hair_colour, :beard, :moustache]
  end
end

app/controllers/people_controller.rb
# All people involved in a case will have a profile, including their
# description and identifying marks.
class PeopleController < ApplicationController
  def index
  end

  def create
    if @person.save
      redirect_to @person
    else
      render 'new'
    end
  end

  def new
  end

  def show
  end

  def edit
  end

  def update
    if @person.update!(person_params)
      redirect_to @person
    else
      render 'edit'
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:gender, :height,
                                   :build, :eye_colour, :hair_colour,
                                   :hair_length, :moustache, :beard,
                                   :ic, aliases_attributes: [
                                     :id, :_destroy, :name])
  end
end

app/helpers/people_helper.rb
# Helper methods for people views
module PeopleHelper
  # @param [Person] person person to attach event to
  # @param [Integer] person person id to attach event to
  # @param [Symbol] type of event, defaults to :birth
  # @return path to create a new event for this person
  def new_personal_event_path(person, type = :birth)
    new_event_path(
      event: {
        event_people_attributes: {
          '0' => {
            person_id: person,
            category: type
          }
        }
      }
    )
  end

  # @param [Person] person person
  # @mark [Mark] mark to edit
  # @return Link to edit a person's mark
  def edit_mark_link(person, mark)
    link_to(t('.editMark'), edit_person_mark_path(person, mark))
  end
end

app/views/people/_aliases.html.erb
<%= a.label :name %>
<%= a.text_field :name %>
<%= a.link_to_remove t('.removeAlias')%>

app/views/people/_form.html.erb
<%= render 'error', :errors => @person.errors %>

<%= nested_form_for @person do |f| %>
    <%= content_tag :h2, t('.aliases') %>
    <%= f.fields_for :aliases do |a| %>
    <%= render 'aliases', :a => a %>
    <% end %>
    <%= f.link_to_add t('.addAlias'), :aliases %>

    <%= f.label :gender %>
    <%= f.select(:gender,
	Person.genders.keys.map {
	|g| [g.titleize,g]}) %>

    <%= f.label :ic %>
    <%= f.select(:ic,
	Person.ics.keys.map {
	|g| [g.titleize,g]}) %>    
    
    <%= f.label :height %>
    <%= f.select(:height,
	Person.heights.keys.map {
	|g| [g.titleize,g]}) %>

    <%= f.label :build %>
    <%= f.select(:build,
	Person.builds.keys.map {
	|g| [g.titleize,g]}) %>

    <%= f.label :eye_colour %>
    <%= f.select(:eye_colour,
	Person.eye_colours.keys.map {
	|g| [g.titleize,g]}) %>
 
    <%= f.label :hair_colour %>
    <%= f.select(:hair_colour,
	Person.hair_colours.keys.map {
	|g| [g.titleize,g]}) %>

    <%= f.label :hair_length %>
    <%= f.select(:hair_length,
	Person.hair_lengths.keys.map {
	|g| [g.titleize,g]}) %>

    <%= f.label :moustache %>
    <%= f.select(:moustache,
	Person.moustaches.keys.map {
	|g| [g.titleize,g]}) %>

    <%= f.label :beard %>
    <%= f.select(:beard,
	Person.beards.keys.map {
	|g| [g.titleize,g]}) %>

    <%= f.submit %>
<% end %>

app/views/people/_person.erb
<%= div_for(person) do %>
<% cache(person) do %>
<%= link_to(person.name,person) %>
<% end %>
<% end %>

app/views/people/index.html.erb
<% content_for(:sidebar, link_to(t('.new'), new_person_path))%>

<%= render @people %>
<%= paginate @people %>

app/views/people/show.html.erb
<%= content_for :title, @person.name %>
<% cache(@person) do %>
	<% content_for(:sidebar) do %>
		<%= link_to t('.edit'), edit_person_path(@person) %>
		<%= link_to t('.delete'), @person, method: :delete, data: { confirm: t('.delete_confirm') }%>
		<%= link_to t('.addBirth'), new_personal_event_path(@person,:birth) if
			@person.birth.empty? %>
		<%= link_to t('.addDeath'), new_personal_event_path(@person,:death) if
		    @person.death.empty? %>
		<%= link_to t('.newMark'), new_person_mark_path(@person) %>
	<% end %>
	<%= content_tag :p do %>
		<%= t('.birth', date: l(@person.dob, format: :formal)) unless @person.dob.nil? %>
		<%= t('.death', date: l(@person.dod, format: formal)) unless @person.dod.nil? %>
	<% end %>
	<%= content_tag :h2, t('.aliases') %>
	<%= render partial: :alias,
	collection: @person.aliases,
	as: :item %>
	
	<%= content_tag :h2, t('.description') %>
	<%= content_tag :dl do %>
		<% @person.description.each do |k,v|%>
			<%= content_tag :dt, k %>
			<%= content_tag :dd, v %>
			<% end %>
		<%= content_tag :p, t('.noDescription') unless
			@person.description.size > 0 %>
	<% end %>
	<%= content_tag :h2, t('.marks') %>
	<%= content_tag :dl do %>
	<% @person.marks.each do |v|%>
	<%= content_tag(:dt) do %>
	<%= v.path %>
	<%=edit_mark_link(@person, v)%>
	<% end %>
			<%= content_tag :dd, v.description %>
			<% end %>
		<%= content_tag :p, t('.noMarks') unless
			@person.marks.size > 0 %>
	<% end %>
	<%= content_tag :h2, t('.story') %>
	<%= render @person.events %>
<% end %>