config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get	'index', to: 'home#index'
  get	'about', to: 'home#about'

  [404,422,500].each do |code|
    get "#{code}", :to => "errors#show", :code => code, :defaults => {:format => :html}
  end

  resources :case_files
  resources :events
  resources :locations
  resources :people do
    resources :marks
  end
  # Configurables
  resources :anatomies
  resources :mark_types
  
  # Auth
  resources :users 
  resources :session, only: [:new,:create,:destroy]
end

app/models/case_file.rb
# A {CaseFile} is a grouping of the other core models. The model
# provides the "story" of the case, using {Person}, {Event},
# {Location} to give the narrative.
#
# Assigning an {Event} to a {CaseFile} will show the event in all
# apropriate views. Conversly not assigning the {Event} a {CaseFile}
# will hide it from view. This can be useful for background
# information (such as birth events which are largely incidental to
# the case.
class CaseFile < ActiveRecord::Base
  # @!attribute [rw] events
  # A case file has many events, these provide the narrative for the
  # case
  has_many :events
  has_many :event_people,
           through: :events
  # @!attribute [r] people
  # The people involved in this case. This is an indirect
  # association. People can only be assigned to the case via an event
  # (i.e. only if they participated in some way).
  has_many :people,
           through: :event_people
  # @!attribute [rw] brief
  # The case brief. This should include an overview of the case and
  # its outcome as a Markdown document.
  validates :brief,
            presence: true,
            length: { minimum: 50 }
  # @!attribute [rw] name
  # The name of the case should be a "descriptive tag" such as 'Jack
  # the Ripper' or 'Jeremy Bamber'. This is what most people should
  # recognise.
  validates :name,
            presence: true

  def tagline
    return brief.split('. ').first if
      super.nil?
    super
  end

  EventPerson.categories.each do |type|
    has_many type[0].pluralize.to_sym,
             -> { where 'event_people.category' => type[0].to_sym },
             through: :event_people,
             source: :person
  end
end

app/controllers/case_files_controller.rb
# Case Files are the core of the website. They can be thought of as
# the folders for events, people and all other models.
class CaseFilesController < ApplicationController
  def index
  end

  def create
    if @case_file.save
      redirect_to @case_file
    else
      render 'new'
    end
  end

  def new
  end

  def show
  end

  def edit
  end

  def update
    if @case_file.update(case_file_params)
      redirect_to @case_file
    else
      render 'edit'
    end
  end

  def destroy
    @case_file.destroy
    redirect_to CaseFile
  end

  # Define case event linking and unlinking
  def link
    @case_file = CaseFile.find(params[:id])
    @event = Event.all
  end

  private

  def case_file_params
    params.require(:case_file).permit(:name, :brief)
  end
end

app/views/case_files/_case_file.html.erb
<%= div_for(case_file) do %>
<% cache(case_file) do %>
<%= link_to(case_file.name,case_file) %>
<% end %>
<% end %>

app/views/case_files/_form.html.erb
<%= render partial: 'error', locals: {errors: @case_file.errors} %>
<%= form_for @case_file do |f|%>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :brief %>
	<%= f.text_area :brief %>
	<%= f.submit %>
<% end %>

app/views/case_files/index.html.erb
<% content_for(:sidebar, link_to(t('.new'), new_case_file_path))%>

<%= render @case_files %>
<%= paginate @case_files %>

app/views/case_files/show.html.erb
<% content_for :title, @case_file.name %>

<% content_for :sidebar do %>
   <%= link_to(t('.new'), new_event_path(event: {case_file_id: @case_file})) %>
   <%= link_to(t('.edit'), edit_event_path) %>
<% end %>
   
<%= content_tag :h2, t('.brief') %>
<% cache(@case_file) do %>
<%= markdown @case_file.brief %>
<% end %>
<%= content_tag :h2, t('.story') %>
<%= render @case_file.events %>