config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get	'index', to: 'home#index'
  get	'about', to: 'home#about'

  [404,422,500].each do |code|
    get "#{code}", :to => "errors#show", :code => code, :defaults => {:format => :html}
  end

  resources :case_files
  resources :events
  resources :locations
  resources :people do
    resources :marks
  end
  # Configurables
  resources :anatomies
  resources :mark_types
  
  # Auth
  resources :users 
  resources :session, only: [:new,:create,:destroy]
end

app/controllers/application_controller.rb
# all controllers inherit from this. Actions here affect every
# controller.
class ApplicationController < ActionController::Base
  load_and_authorize_resource
  before_action :paginate_resource, only: [:index]

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # check_authorization
  rescue_from CanCan::AccessDenied do |e|
    @message = e.message
    render 'errors/403', status: 403
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    flash[:alert] = e.message
    redirect_to action: :index
  end

  def current_user
    User.find_by_id session[:user_id]
  end

  def paginate_resource
    current = instance_variable_get("@#{controller_name}")
    return nil if current.nil?
    instance_variable_set("@#{controller_name}",
                          current.page(params[:page]))
  end
end

app/helpers/application_helper.rb
# Helper method for all Views
module ApplicationHelper
  # @return [Boolean] true when there is a user signed in.
  def signed_in?
    if !session[:user_id].nil?
      true
    else
      false
    end
  end

  # @return [String] the name of the current user
  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end

  # Gets the title of the current page. This is used by the layout
  # engine and probably shouldn't be called elsewhere.
  # @return the page title
  def title
    return "CaseDB - #{content_for :title}" if content_for? :title
    default_title
  end

  # Returns the current style. This is used by the layout engine and
  # shouldn't be called elsewhere.
  # @return the current style for this user
  def style
    theme = 'themes/wine'
    theme = "themes/#{current_user.theme}" unless
      current_user.nil? || current_user.theme.nil?
    theme
  end

  # Returns a default title for the page, this will usually be
  # "controller_action" and an attempt will be made to localise the
  # string. To override this title for a page define content for
  # :title anywhere in the page.
  # @return default title for this page
  def default_title
    t("headers.#{controller_name}.#{action_name}")
  end
end

app/views/application/_body.html.erb
<%= render 'header' %>
<%= render 'navigation' %>
<%= render 'flash' %>
<%= content_tag(:h1) do %>
<% if content_for? :title %>
<%= yield(:title) %>
<% else %>
<%= title %>
<% end %>
<% end %>
<%= content_tag(:main) do %>
<% if content_for?(:sidebar) %>
<%= content_tag(:aside) do %>
<%= yield :sidebar %>
<% end %>
<% end %>
<%= content_tag(:section) do %>
<%= yield %>
<% end %>
<% end %>
<% cache do %>
<%= render 'footer'%>
<% end %>

app/views/application/_error.html.erb
<% if errors.any? %>
    <%= content_tag(:h2) do %>
      <%= pluralize(errors.count, "error") %> 
      <%= t('validation.preventsave')%>:
    <% end %>
  <%= content_tag(:ul, :class => "error display") do %>
    <% errors.full_messages.each do |e| %>
      <%= content_tag(:li, :class => "error") do %>
	<%= e %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/application/_flash.html.erb
<% if notice %>
	<%= content_tag :section, class: "flash notice" do%>
		<%= notice %>
	<%  end %>
<% end %>
<% if alert %>
	<%= content_tag :section, class: "flash alert" do%>
		<%= alert %>
	<%  end %>
<% end %>

app/views/application/_footer.html.erb
<%= content_tag(:footer) do %>
  <%=markdown t('.footer')%>
<% end %>

  

app/views/application/_head.html.erb
	<%= content_tag(:title, title) %>
	<%= stylesheet_link_tag style, media: 'all' %>
	<%= javascript_include_tag :application %>
	<%= favicon_link_tag('favicon.png') %>
	<%= tag(:meta, name: "viewport", content: "width=device-width", 'initial-scale' => "1", 'user-scalable' => 'no') %>
	<%= tag(:meta, charset: "UTF-8") %>
	<%= tag(:meta, name: "description", content: t('.description')) %>
	<%= csrf_meta_tags %>

app/views/application/_header.html.erb
<%= content_tag(:header) do %>
  <%=t('.header')%>
<% end %>

app/views/application/_navigation.html.erb
<%= content_tag(:nav) do %>
<% cache do %>
	<%= link_to t('.home'), index_path %>
	<%= link_to t('.case_files'), case_files_path %>
	<%= link_to t('.people'), people_path %>
	<%= link_to t('.about'), about_path %>
	<%= content_tag(:div, class: :account ) do %>
<% end %>
	<% if signed_in? %>
	<%= link_to current_user.username, user_path(current_user) %>
	<% else %>
	<%= link_to t(".login"), new_session_path %>
	<%= link_to t(".register"), new_user_path %>
	<% end %>
	<% end %>
<% end %>

app/views/application/edit.html.erb
<%= render partial: 'form' %>

app/views/application/new.html.erb
<%=  render partial: 'forms/event'%>