config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get	'index', to: 'home#index'
  get	'about', to: 'home#about'

  [404,422,500].each do |code|
    get "#{code}", :to => "errors#show", :code => code, :defaults => {:format => :html}
  end

  resources :case_files
  resources :events
  resources :locations
  resources :people do
    resources :marks
  end
  # Configurables
  resources :anatomies
  resources :mark_types
  
  # Auth
  resources :users 
  resources :session, only: [:new,:create,:destroy]
end

app/models/anatomy.rb
# The anatomy model is a hierarchical list of all possible anatomical
# locations. The purpose of this model is to locate a {Mark} on a {Person}.
#
# The functionality should be consumed by {Mark}
#
# @see Mark
# @see MarkType
# @see Person
class Anatomy < ActiveRecord::Base
  acts_as_nested_set

  # Get the path to the current object. This will be a string
  # containing the name of this element as well as all ancestors.
  # @return [String] path to this object.
  def path
    path = ''
    ancestors.each do |anc|
      path += "#{anc.name}/"
    end
    path += name
    path
  end

  # @!attribute [rw] name
  # The name of this part.
end

app/controllers/anatomies_controller.rb
# Anatomies are selectable body parts which allow the Mark model to be
# linked to a location on a person's body.
class AnatomiesController < ApplicationController
  # GET /anatomies
  def index
  end

  # GET /anatomies/1
  def show
  end

  # GET /anatomies/new
  def new
  end

  # GET /anatomies/1/edit
  def edit
  end

  # POST /anatomies
  def create
    @anatomy = Anatomy.new(anatomy_params)

    if @anatomy.save
      redirect_to @anatomy, notice: 'Anatomy was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /anatomies/1
  def update
    if @anatomy.update(anatomy_params)
      redirect_to @anatomy, notice: 'Anatomy was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /anatomies/1
  def destroy
    @anatomy.destroy
    redirect_to anatomies_url, notice: 'Anatomy was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def anatomy_params
    params.require(:anatomy).permit(:name, :parent_id)
  end
end

app/helpers/anatomies_helper.rb
# Helper methods for Anatomy Views
module AnatomiesHelper
  # @param [Anatomy] parent parent of the new element
  # @param [Integer] parent parent of the new element
  # @return the path for a new "anatomy" with parent as the parent
  def new_child_anatomy_path(parent)
    new_anatomy_path(
      anatomy: {
        parent_id: parent
      }
    )
  end
end

app/views/anatomies/_anatomy.erb
<%= div_for(anatomy) do %>
<% cache(anatomy) do %>
<%= link_to(anatomy.path, anatomy)%>
<% end %>
<% end %>

app/views/anatomies/_form.html.erb
<%= render 'error', :errors => @anatomy.errors %>

<%= nested_form_for @anatomy do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :parent_id %>
<%= f.collection_select :parent_id,
    Anatomy.all, :id, :path %>

<%= f.submit %>
<% end %>

app/views/anatomies/index.html.erb
<% content_for(:sidebar, link_to(t('.new'), new_anatomy_path))%>

<%= render @anatomies %>
<%= paginate @anatomies %>

app/views/anatomies/show.html.erb
<%= content_for :title, @anatomy.name %>
<% content_for :sidebar do %>
<%= link_to t('.newChild'), new_child_anatomy_path(@anatomy) %>
<%= link_to t('.edit'), edit_anatomy_path(@anatomy) %>
<%= link_to t('.delete'), anatomy_path(@anatomy), method: :delete %>
<% end %>
<% cache(@anatomy) do %>
<%= @anatomy.path %>
<% end %>